config/routes.rb
Rails.application.routes.draw do
  resources :habits

  devise_for :users
  resources :users

  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

 

end

app/models/habit.rb
class Habit < ActiveRecord::Base
	validates :aftertrigger, :length => { :minimum => 2, :message => "has invalid length"},
        :presence => {:message => "can't be blank"}
  	validates :behavior, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	before_destroy :unsubscribe_user_from_mailing_list
  enum role: [:student, :admin]
	after_initialize :set_default_role, :if => :new_record?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :habits, :dependent => :destroy
  accepts_nested_attributes_for :habits, allow_destroy: true
  after_create :subscribe_user_to_mailing_list



   def set_default_role
   	self.role ||= :student
   end

   private

  def subscribe_user_to_mailing_list
    SubscribeUserToMailingListJob.perform_later(self)
  end

  def unsubscribe_user_from_mailing_list
    UnsubscribeDeletedUserJob.perform_later(self)
  end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) } #here you can permit custom fields. 
  end


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /habits
  # GET /habits.json
  def index
    @user = current_user
    
  end

  # GET /habits/1
  # GET /habits/1.json
  def show
  end

  # GET /habits/new
  def new
    @user  = current_user
    if @user.habits.count >= 3
      redirect_to habits_path
    end

  end

  # GET /habits/1/edit
  def edit
  end
  

  # POST /habits
  # POST /habits.json
  def create
    @habit = Habit.new(habit_params)
    @habit.user_id = current_user.id

    respond_to do |format|
      if @habit.save
        format.html { redirect_to habits_path, notice: 'Habit was successfully created.' }
        format.json { render :index, status: :created, location: @habit }
      else
        format.html { render :new }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habits/1
  # PATCH/PUT /habits/1.json
  def update
     @habit = Habit.find(params[:id])

    respond_to do |format|
      if @habit.update_attributes(habit_params)
        format.html { redirect_to(@habit, :notice => 'Habit was successfully updated.') }
        format.json { respond_with_bip(@habit) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@habit) }
      end
    end
  end

  # DELETE /habits/1
  # DELETE /habits/1.json
  def destroy
    @habit.destroy
    respond_to do |format|
      format.html { redirect_to habits_url, notice: 'Habit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      @habit = Habit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def habit_params
      params.require(:habit).permit(:aftertrigger, :behavior)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home

  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password habits_attributes: [:aftertrigger, :behavior, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/habits_helper.rb
module HabitsHelper

	def find_real_habits(user)
		user.habits.select {|habit| !habit.aftertrigger.nil? }
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/habits/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this habit from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% 3.times do %>

<%= f.fields_for :habits, @user.habits.build  do |builder| %>

  <div class="field">
    <%= builder.label :aftertrigger %><br>
    <%= builder.text_area :aftertrigger %>
  </div>
  <div class="field">
    <%= builder.label :behavior %><br>
    <%= builder.text_area :behavior %>
  </div>
<% end %>
<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/habits/edit.html.erb
<h1>Editing Habit</h1>


<%= link_to 'Show', @habit %> |
<%= link_to 'Back', habits_path %>

app/views/habits/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.email %>'s habits</h1>

<% find_real_habits(@user).each do |habit| %>


<p><%= best_in_place habit, :aftertrigger, :as => :input, :nil => "Click me to add content!" %>  <span class="glyphicon glyphicon-edit edit"></span></p>
<p><p><%= best_in_place habit, :behavior, :as => :input, :nil => "Click me to add content!" %>   <span class="glyphicon glyphicon-edit edit"></span></p>

<% end %>




<%= link_to 'New Habit', new_habit_path %>

app/views/habits/new.html.erb
<h1>New Habit</h1>

<%= render 'form' %>


<%= link_to 'Back', habits_path %>

app/views/habits/show.html.erb
<p id="notice"><%= notice %></p>

<p> <%= @habit.aftertrigger %></p>

<%= link_to 'Edit', edit_habit_path(@habit) %> |
<%= link_to 'Back', habits_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Mes Minis Habitudes', root_url, :class => "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <% if current_user.present? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-default" %></li>
        <% else %>
          <li><%= link_to "Sign in", '#login',  "data-toggle" => "modal", "data-target" => "#login", :class => "btn btn-default" %></li>
            <li><%= link_to "Create an Account", '#sign_up', "data-toggle" => "modal", "data-target" => "#sign_up", :class => "btn btn-default" %></li>
        <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MmhApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'static_pages/login_modal' %>
<%= render 'static_pages/signup_modal' %>
<div class="container">
	<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>
</div>
</body>
</html>

app/views/static_pages/_login_modal.html.erb
<!-- Login Modal -->
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="logIn" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="logIn">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
		<div>
			<%= f.label :email %><br />
			<%= f.email_field :email, :autofocus => true %></div>
		<div>
			<%= f.label :password %><br />
			<%= f.password_field :password %>
		</div>
		<% if devise_mapping.rememberable? -%>
			<div>
				<%= f.check_box :remember_me %> 
				<%= f.label :remember_me %>
			</div>
	  <% end -%>
		<%= f.submit "Sign in", :class => 'btn btn-small btn-success' %>
	<% end %>
      </div>
      <div class="modal-footer">
       <%= link_to "Create an Account", '#', :class => "btn btn-default", :id => "createAccount" %>
  
        <%= link_to "Forgot Password?", new_user_password_path %>
       
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_signup_modal.html.erb
<!-- SignUp Modal -->
<div class="modal fade" id="sign_up" tabindex="-1" role="dialog" aria-labelledby="signUp" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="signUp">Sign up!</h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
		<%= devise_error_messages! %>
		<div>
			<%= f.label :name %><br />
			<%= f.text_field :name, :autofocus => true %>
		</div>
		<div>
			<%= f.label :email %><br />
			<%= f.email_field :email, :autofocus => true %>
		</div>
		<div>
			<%= f.label :password %><br />
			<%= f.password_field :password %></div>
			<p><div><%= f.submit "Sign up", :class => 'btn btn-small btn-success' %></div></p>
		</div>
	<% end %>
      <div class="modal-footer">
      	<%= link_to "Already have an account?", '#', :class => "btn btn-default", :id => "signIn" %>
      	<%= link_to "Forgot Password?", new_user_password_path %>
  
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>

<p> In the app  - introduction to the concept of mes minis habitudes</p>
<%= link_to "Want to create some habits?", new_habit_path, class: "btn btn-lg btn-danger" %>


<% else %>

<div class="jumbotron">
 	<h2>Stage de 5 Jours</h2>
    <h1>Et si vous pouviez apprendre à vous créér de nouvelles habitudes et vous y tenir ? </h1>
     
     <p>
 
 
        </p>
     <div class="row">
     	<div class="col-sm-6">
     		<h2>Je m’inscris gratuitement</h2>
     	<p>C'est pour vous si vous procrastinez face à un gros challenge, vous voulez vous construire de meilleures habitudes de vie, vous levez plus tôt ou vous remettre au sport, vous voulez être mieux organisé, etc…</p>

     	</div>
    <div class="col-sm-6"> 
    	<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
		<%= devise_error_messages! %>
		<div>
			<%= f.label :name %><br />
			<%= f.text_field :name, :autofocus => true %>
		</div>
		<div>
			<%= f.label :email %><br />
			<%= f.email_field :email, :autofocus => true %>
		</div>
		<div>
			<%= f.label :password %><br />
			<%= f.password_field :password %></div>
			<p><div><%= f.submit "Sign up", :class => 'btn btn-small btn-success' %></div></p>
		<% end %>
		</div>
	</div><!-- close the row -->
</div>   

 <% end %>

app/views/static_pages/signup_modal.html.erb
<div class="modal hide fade in" id="sign_up">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h2>Sign Up</h2>
	</div>
<div class="modal-body">
	<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
		<%= devise_error_messages! %>
		<div><%= f.label :email %><br />
		<%= f.email_field :email, :autofocus => true %></div>
		<div><%= f.label :password %><br />
		<%= f.password_field :password %></div>
		<div><%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %></div>
		</div>
	<div class="modal-footer">
		<p><div><%= f.submit "Sign up", :class => 'btn btn-small btn-success' %></div></p>
		<p><a href="#" class="btn btn-small" data-dismiss="modal">Close</a></p>
	</div>
	<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>